minimumReleaseAge: 0

shellEmulator: true

trustPolicy: off

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "@vaadin/vaadin-usage-statistics"
  - core-js

allowBuilds:
  "@vaadin/vaadin-usage-statistics": false
  core-js: true
